[package]
name = "re-node"
description = "Sovereign Rust-native JavaScript Runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
re-core.workspace = true
anyhow.workspace = true
clap.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
boa_engine = "0.19"
boa_runtime = "0.19"

[[bin]]
name = "re-node"
path = "src/main.rs"
