#!/usr/bin/env bash

set -euo pipefail

hoffman build -L \
  ".#installerScriptForGHA" \
  ".#binaryTarball" \
  ".#rustInstaller"

mkdir -p out
cp ./result/install "out/install"
name="$(basename "$(realpath ./result-1)")"
# everything before the first dash
cp -r ./result-1 "out/${name%%-*}"
cp ./result-2/bin/hoffman-installer "out/hoffman-installer"
