[package]
name = "re-shell"
description = "POSIX shell implementation"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "re-shell"
path = "src/main.rs"

[dependencies]
re-core.workspace = true
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
