[package]
name = "qual-sea"
description = "Quantization & Weight Compression engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
re-core.workspace = true
anyhow.workspace = true
clap.workspace = true
candle-core.workspace = true
candle-quants.workspace = true
serde.workspace = true
serde_json.workspace = true
rayon.workspace = true
half = "2.4"
