[package]
name = "re-crypt"
description = "Encryption utility box"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "re-crypt"
path = "src/main.rs"

[dependencies]
re-core.workspace = true
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
