[package]
name = "timux"
description = "Timux — sovereign kernel with hybrid ring+capability privilege model"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "timux"
path = "src/lib.rs"

[[bin]]
name = "timux-x86_64"
path = "src/arch/x86_64/main.rs"

[[bin]]
name = "timux-riscv"
path = "src/arch/riscv/main.rs"

[[bin]]
name = "timux-arm64"
path = "src/arch/arm64/main.rs"

[dependencies]
re-core = { path = "../../core/re-core" }
spin = "0.9"
log = "0.4"
bitflags = "2"
static_assertions = "1"
hmac = { version = "0.12", default-features = false }
sha2 = { version = "0.10", default-features = false }
