[package]
name = "sushi"
description = "A native, high-performance desktop GUI framework"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
re-core.workspace = true
eframe = "0.27" # The elite native GUI engine for Rust
serde = { version = "1", features = ["derive"] }

[[bin]]
name = "sushi-demo"
path = "examples/demo.rs"
