//! Scaffold — writes a complete sovereign OS workspace to disk.
  //!
  //! Every file generated by Oxidiser flows through this module.
  //! It reads the `OsConfig`, calls the appropriate template functions,
  //! and writes the results into the output directory tree.

  use std::fs;
  use std::path::{Path, PathBuf};
  use anyhow::{Context, Result};
  use crate::config::OsConfig;
  use crate::templates;

  // ─── Public entry point ───────────────────────────────────────────────────────

  /// Generate the full workspace for `cfg` at `cfg.output_dir`.
  /// Prints a status line for every file written.
  pub fn generate(cfg: &OsConfig) -> Result<()> {
      let root = &cfg.output_dir;

      print_header(cfg);

      // ── Workspace root ────────────────────────────────────────────────────────
      write(root, "Cargo.toml",          &templates::root_cargo(cfg))?;
      write(root, "rust-toolchain.toml", &templates::rust_toolchain(cfg))?;
      write(root, ".cargo/config.toml",  &templates::cargo_config(cfg))?;
      write(root, ".gitignore",           templates::gitignore())?;
      write(root, "README.md",           &templates::workspace_readme(cfg))?;

      // ── kernel/<slug> ─────────────────────────────────────────────────────────
      let kdir = format!("kernel/{}", cfg.slug);
      write(root, &format!("{kdir}/Cargo.toml"),                  &templates::kernel_cargo(cfg))?;
      write(root, &format!("{kdir}/src/lib.rs"),                  &templates::kernel_lib(cfg))?;
      write(root, &format!("{kdir}/src/cap.rs"),                  &templates::kernel_cap(cfg))?;
      write(root, &format!("{kdir}/src/mm/mod.rs"),               &templates::kernel_mm(cfg))?;
      write(root, &format!("{kdir}/src/mm/allocator.rs"),         &templates::kernel_mm_allocator(cfg))?;
      write(root, &format!("{kdir}/src/sched/mod.rs"),            &templates::kernel_sched(cfg))?;
      write(root, &format!("{kdir}/src/ipc/mod.rs"),              &templates::kernel_ipc(cfg))?;
      write(root, &format!("{kdir}/src/subkernel/mod.rs"),        &templates::kernel_subkernel_mod(cfg))?;
      write(root, &format!("{kdir}/src/subkernel/instance.rs"),   &templates::kernel_subkernel_instance(cfg))?;
      write(root, &format!("{kdir}/src/subkernel/manager.rs"),    &templates::kernel_subkernel_manager(cfg))?;

      // ── core/<slug>-core ──────────────────────────────────────────────────────
      let cdir = format!("core/{}-core", cfg.slug);
      write(root, &format!("{cdir}/Cargo.toml"),   &templates::core_cargo(cfg))?;
      write(root, &format!("{cdir}/src/lib.rs"),   &templates::core_lib(cfg))?;
      write(root, &format!("{cdir}/src/types.rs"), &templates::core_types(cfg))?;

      // ── boot/<slug>-boot ──────────────────────────────────────────────────────
      let bdir = format!("boot/{}-boot", cfg.slug);
      write(root, &format!("{bdir}/Cargo.toml"),   &templates::boot_cargo(cfg))?;
      write(root, &format!("{bdir}/src/main.rs"),  &templates::boot_main(cfg))?;

      // ── Optional feature crates ───────────────────────────────────────────────
      if cfg.features.networking {
          scaffold_net(root, cfg)?;
      }
      if cfg.features.ai {
          scaffold_llm(root, cfg)?;
      }
      if cfg.features.blueprint {
          scaffold_blueprint(root, cfg)?;
      }

      print_summary(cfg);
      Ok(())
  }

  // ─── Optional: networking sub-kernel ─────────────────────────────────────────

  fn scaffold_net(root: &Path, cfg: &OsConfig) -> Result<()> {
      let dir = format!("runtimes/{}-net", cfg.slug);
      write(root, &format!("{dir}/Cargo.toml"), &net_cargo(cfg))?;
      write(root, &format!("{dir}/src/lib.rs"), &net_lib(cfg))?;
      Ok(())
  }

  fn net_cargo(cfg: &OsConfig) -> String {
      format!(
          "[package]\nname = \"{slug}-net\"\ndescription = \"{name} capability-gated network stack\"\nversion.workspace = true\nedition.workspace = true\nauthors.workspace = true\nlicense.workspace = true\n\n[lib]\npath = \"src/lib.rs\"\n\n[dependencies]\nanyhow = {{ workspace = true }}\nthiserror = \"1\"\n",
          slug = cfg.slug, name = cfg.name
      )
  }

  fn net_lib(cfg: &OsConfig) -> String {
      format!(
          "//! {name} network stack sub-kernel\n//! Capability-gated TCP/UDP — see re-net for reference implementation.\n\npub mod socket;\npub mod tcp;\npub mod udp;\n\npub use socket::NetError;\n",
          name = cfg.name
      )
  }

  // ─── Optional: AI inference sub-kernel ───────────────────────────────────────

  fn scaffold_llm(root: &Path, cfg: &OsConfig) -> Result<()> {
      let dir = format!("runtimes/{}-llm", cfg.slug);
      write(root, &format!("{dir}/Cargo.toml"), &llm_cargo(cfg))?;
      write(root, &format!("{dir}/src/lib.rs"), &llm_lib(cfg))?;
      Ok(())
  }

  fn llm_cargo(cfg: &OsConfig) -> String {
      format!(
          "[package]\nname = \"{slug}-llm\"\ndescription = \"{name} AI inference runtime\"\nversion.workspace = true\nedition.workspace = true\nauthors.workspace = true\nlicense.workspace = true\n\n[lib]\npath = \"src/lib.rs\"\n\n[dependencies]\nanyhow = {{ workspace = true }}\n",
          slug = cfg.slug, name = cfg.name
      )
  }

  fn llm_lib(cfg: &OsConfig) -> String {
      format!(
          "//! {name} LLM inference runtime\n//! Stub — wire up candle-core for full inference.\n\npub struct InferenceEngine;\n\nimpl InferenceEngine {{\n    pub fn new() -> Self {{ Self }}\n    pub fn infer(&self, prompt: &str) -> String {{\n        format!(\"[{name}-llm] inference of: {{prompt}}\")\n    }}\n}}\n",
          name = cfg.name
      )
  }

  // ─── Optional: blueprint editor ──────────────────────────────────────────────

  fn scaffold_blueprint(root: &Path, cfg: &OsConfig) -> Result<()> {
      let dir = format!("utilities/{}-blueprint", cfg.slug);
      write(root, &format!("{dir}/Cargo.toml"), &bp_cargo(cfg))?;
      write(root, &format!("{dir}/src/lib.rs"), &bp_lib(cfg))?;
      Ok(())
  }

  fn bp_cargo(cfg: &OsConfig) -> String {
      format!(
          "[package]\nname = \"{slug}-blueprint\"\ndescription = \"{name} boot blueprint editor\"\nversion.workspace = true\nedition.workspace = true\nauthors.workspace = true\nlicense.workspace = true\n\n[lib]\npath = \"src/lib.rs\"\n\n[dependencies]\nserde = {{ workspace = true }}\nserde_json = {{ workspace = true }}\n",
          slug = cfg.slug, name = cfg.name
      )
  }

  fn bp_lib(cfg: &OsConfig) -> String {
      format!(
          "//! {name} blueprint editor\n//! Stub — see re-blueprint for the full implementation.\n\nuse serde::{{Serialize, Deserialize}};\n\n#[derive(Debug, Serialize, Deserialize)]\npub struct Blueprint {{\n    pub name:    String,\n    pub version: u32,\n    pub entries: Vec<String>,\n}}\n\nimpl Blueprint {{\n    pub fn new(name: &str) -> Self {{\n        Self {{ name: name.into(), version: 1, entries: Vec::new() }}\n    }}\n}}\n",
          name = cfg.name
      )
  }

  // ─── File writer ─────────────────────────────────────────────────────────────

  fn write(root: &Path, rel_path: &str, content: &str) -> Result<()> {
      let path = root.join(rel_path);
      if let Some(parent) = path.parent() {
          fs::create_dir_all(parent)
              .with_context(|| format!("create dirs for {}", path.display()))?;
      }
      fs::write(&path, content)
          .with_context(|| format!("write {}", path.display()))?;
      println!("  ✓  {rel_path}");
      Ok(())
  }

  // ─── Pretty output ────────────────────────────────────────────────────────────

  fn print_header(cfg: &OsConfig) {
      println!();
      println!("╔══════════════════════════════════════════════════════╗");
      println!("║          OXIDISER — Sovereign OS Generator           ║");
      println!("╠══════════════════════════════════════════════════════╣");
      println!("║  OS Name   : {:<40}║", cfg.name);
      println!("║  Slug      : {:<40}║", cfg.slug);
      println!("║  Arch      : {:<40}║", cfg.arch.display());
      println!("║  Output    : {:<40}║", cfg.output_dir.display().to_string().chars().take(40).collect::<String>());
      println!("╚══════════════════════════════════════════════════════╝");
      println!();
      println!("Generating workspace files:");
  }

  fn print_summary(cfg: &OsConfig) {
      let feats = cfg.features.enabled_list();
      println!();
      println!("╔══════════════════════════════════════════════════════╗");
      println!("║  ✅  {} sovereign OS generated successfully!", cfg.name);
      println!("╠══════════════════════════════════════════════════════╣");
      if feats.is_empty() {
          println!("║  Features : minimal (no optional modules)            ║");
      } else {
          for f in &feats {
              println!("║  ✓  {:<48}║", f);
          }
      }
      println!("╠══════════════════════════════════════════════════════╣");
      println!("║  Next steps:                                         ║");
      println!("║    cd {}  ║", cfg.output_dir.display().to_string().chars().take(43).collect::<String>());
      println!("║    cargo build                                       ║");
      println!("╚══════════════════════════════════════════════════════╝");
      println!();
  }
  