//! File content templates for a generated sovereign OS workspace.
  //!
  //! Every template is a function that takes an `&OsConfig` and returns
  //! a `String` — the exact file content to write to disk.

  use crate::config::{OsConfig, TargetArch};

  // ─── Root Cargo.toml ─────────────────────────────────────────────────────────

  pub fn root_cargo(cfg: &OsConfig) -> String {
      let mut members = format!(
          "    "kernel/{name}",\n    "core/{name}-core",\n    "boot/{name}-boot",",
          name = cfg.slug
      );
      if cfg.features.networking { members.push_str(&format!("\n    "runtimes/{}-net",", cfg.slug)); }
      if cfg.features.ai         { members.push_str(&format!("\n    "runtimes/{}-llm",", cfg.slug)); }
      if cfg.features.blueprint  { members.push_str(&format!("\n    "utilities/{}-blueprint",", cfg.slug)); }

      format!(r#"[workspace]
  resolver = "2"
  members = [
  {members}
  ]

  [workspace.package]
  version      = "{ver}"
  edition      = "{ed}"
  authors      = ["{author}"]
  license      = "AGPL-3.0"
  repository   = ""

  [workspace.dependencies]
  anyhow    = "1"
  thiserror = "1"
  log       = "0.4"
  serde     = {{ version = "1", features = ["derive"] }}
  serde_json = "1"
  toml       = "0.8"
  clap       = {{ version = "4", features = ["derive"] }}
  "#,
          members = members,
          ver     = cfg.version,
          ed      = cfg.edition,
          author  = cfg.author,
      )
  }

  // ─── rust-toolchain.toml ─────────────────────────────────────────────────────

  pub fn rust_toolchain(cfg: &OsConfig) -> String {
      let target = cfg.arch.rust_target();
      format!(r#"[toolchain]
  channel  = "nightly"
  targets  = ["{target}"]
  components = ["rust-src", "rustfmt", "clippy"]
  "#)
  }

  // ─── .cargo/config.toml ──────────────────────────────────────────────────────

  pub fn cargo_config(cfg: &OsConfig) -> String {
      let target = cfg.arch.rust_target();
      format!(r#"[build]
  target = "{target}"

  [unstable]
  build-std = ["core", "compiler_builtins", "alloc"]
  build-std-features = ["compiler-builtins-mem"]
  "#)
  }

  // ─── Kernel Cargo.toml ───────────────────────────────────────────────────────

  pub fn kernel_cargo(cfg: &OsConfig) -> String {
      format!(r#"[package]
  name        = "{slug}-kernel"
  description = "{name} sovereign kernel"
  version.workspace = true
  edition.workspace = true
  authors.workspace = true
  license.workspace = true

  [lib]
  path = "src/lib.rs"

  [dependencies]
  {slug}-core = {{ path = "../../core/{slug}-core" }}
  log         = {{ workspace = true }}

  [profile.dev]
  panic = "abort"

  [profile.release]
  panic   = "abort"
  lto     = true
  opt-level = "s"
  "#, slug = cfg.slug, name = cfg.name)
  }

  // ─── Kernel lib.rs ───────────────────────────────────────────────────────────

  pub fn kernel_lib(cfg: &OsConfig) -> String {
      let mut mods = String::from(
          "pub mod cap;
pub mod mm;
pub mod sched;
pub mod ipc;
pub mod subkernel;
"
      );
      if cfg.features.filesystem  { mods.push_str("pub mod ikfs;
"); }
      if cfg.features.networking  { mods.push_str("pub mod net;
"); }
      if cfg.features.crypto      { mods.push_str("pub mod crypto;
"); }
      if cfg.features.shadow      { mods.push_str("// ShadowManager re-exported from subkernel
"); }

      format!(r#"//! {name} — Sovereign Kernel
  //!
  //! Generated by Oxidiser. Do not edit this header.
  #![no_std]
  extern crate alloc;

  {mods}
  pub use cap::{{CapabilityToken, CapRight}};
  pub use subkernel::{{SubKernel, SubKernelId, SubKernelManager}};
  "#, name = cfg.name, mods = mods)
  }

  // ─── cap.rs ──────────────────────────────────────────────────────────────────

  pub fn kernel_cap(cfg: &OsConfig) -> String {
      format!(r#"//! Capability system for {name}
  extern crate alloc;

  use alloc::string::String;

  bitflags::bitflags! {{
      #[derive(Debug, Clone, Copy, PartialEq, Eq)]
      pub struct CapRight: u64 {{
          const READ          = 1 << 0;
          const WRITE         = 1 << 1;
          const EXEC          = 1 << 2;
          const MAP           = 1 << 3;
          const SEND          = 1 << 4;
          const RECV          = 1 << 5;
          const PROCESS_SPAWN = 1 << 6;
          const FS_READ       = 1 << 7;
          const FS_WRITE      = 1 << 8;
          const NET_SEND      = 1 << 9;
          const NET_RECV      = 1 << 10;
          const CLOCK_READ    = 1 << 11;
          const ADMIN         = 1 << 63;
      }}
  }}

  #[derive(Debug, Clone)]
  pub struct CapabilityToken {{
      pub id:     u64,
      pub rights: CapRight,
      pub expiry: u64,
      valid:      bool,
  }}

  impl CapabilityToken {{
      pub fn new(id: u64, rights: CapRight) -> Self {{
          Self {{ id, rights, expiry: u64::MAX, valid: true }}
      }}
      pub fn root() -> Self {{ Self::new(0, CapRight::all()) }}
      pub fn is_valid(&self) -> bool {{ self.valid }}
      pub fn permits(&self, right: CapRight) -> bool {{ self.valid && self.rights.contains(right) }}
      pub fn revoke(&mut self) {{ self.valid = false; }}
  }}
  "#, name = cfg.name)
  }

  // ─── subkernel/mod.rs ────────────────────────────────────────────────────────

  pub fn kernel_subkernel_mod(cfg: &OsConfig) -> String {
      let mut mods = String::from("pub mod instance;
pub mod manager;
");
      if cfg.features.shadow  { mods.push_str("pub mod shadow;
"); }
      if cfg.features.hotswap { mods.push_str("pub mod hotswap;
"); }

      format!(r#"//! Sub-kernel management for {name}
  extern crate alloc;
  {mods}
  pub use instance::{{SubKernel, SubKernelId, SubKernelConfig, SubKernelState}};
  pub use manager::SubKernelManager;
  "#, name = cfg.name, mods = mods)
  }

  // ─── subkernel/instance.rs ───────────────────────────────────────────────────

  pub fn kernel_subkernel_instance(cfg: &OsConfig) -> String {
      format!(r#"//! SubKernel instance type for {name}
  extern crate alloc;
  use alloc::string::String;
  use crate::cap::CapabilityToken;

  pub type SubKernelId = u64;

  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub enum SubKernelState {{ Stopped, Running, Suspended, Crashed }}

  #[derive(Debug, Clone)]
  pub struct SubKernelConfig {{
      pub name:    &'static str,
      pub mem_mb:  u32,
  }}

  #[derive(Debug)]
  pub struct SubKernel {{
      pub id:     SubKernelId,
      pub config: SubKernelConfig,
      pub state:  SubKernelState,
      pub cap:    CapabilityToken,
      heartbeat:  u64,
  }}

  impl SubKernel {{
      pub fn new(id: SubKernelId, config: SubKernelConfig, cap: CapabilityToken) -> Self {{
          Self {{ id, config, state: SubKernelState::Stopped, cap, heartbeat: 0 }}
      }}
      pub fn start(&mut self)   {{ self.state = SubKernelState::Running; }}
      pub fn stop(&mut self)    {{ self.state = SubKernelState::Stopped; }}
      pub fn suspend(&mut self) {{ self.state = SubKernelState::Suspended; }}
      pub fn tick(&mut self)    {{ if self.state == SubKernelState::Running {{ self.heartbeat += 1; }} }}
      pub fn heartbeat(&self)   -> u64 {{ self.heartbeat }}
      pub fn is_running(&self)  -> bool {{ self.state == SubKernelState::Running }}
  }}
  "#, name = cfg.name)
  }

  // ─── subkernel/manager.rs ────────────────────────────────────────────────────

  pub fn kernel_subkernel_manager(cfg: &OsConfig) -> String {
      format!(r#"//! SubKernelManager for {name}
  extern crate alloc;
  use alloc::vec::Vec;
  use crate::cap::{{CapabilityToken, CapRight}};
  use super::instance::{{SubKernel, SubKernelId, SubKernelConfig, SubKernelState}};

  pub struct SubKernelManager {{
      sks:     Vec<SubKernel>,
      next_id: SubKernelId,
  }}

  impl SubKernelManager {{
      pub fn new() -> Self {{ Self {{ sks: Vec::new(), next_id: 1 }} }}

      pub fn spawn(&mut self, config: SubKernelConfig, cap: CapabilityToken) -> Result<SubKernelId, &'static str> {{
          if !cap.permits(CapRight::PROCESS_SPAWN) {{ return Err("no PROCESS_SPAWN right"); }}
          let id = self.next_id; self.next_id += 1;
          let mut sk = SubKernel::new(id, config, cap);
          sk.start();
          self.sks.push(sk);
          Ok(id)
      }}

      pub fn terminate(&mut self, id: SubKernelId) -> Result<(), &'static str> {{
          let sk = self.get_mut(id).ok_or("not found")?;
          sk.stop(); Ok(())
      }}

      pub fn suspend(&mut self, id: SubKernelId) -> Result<(), &'static str> {{
          let sk = self.get_mut(id).ok_or("not found")?;
          sk.suspend(); Ok(())
      }}

      pub fn tick_all(&mut self) {{ for sk in &mut self.sks {{ sk.tick(); }} }}

      pub fn get(&self, id: SubKernelId) -> Option<&SubKernel> {{
          self.sks.iter().find(|s| s.id == id)
      }}
      fn get_mut(&mut self, id: SubKernelId) -> Option<&mut SubKernel> {{
          self.sks.iter_mut().find(|s| s.id == id)
      }}
      pub fn count(&self) -> usize {{ self.sks.len() }}
      pub fn running(&self) -> usize {{ self.sks.iter().filter(|s| s.is_running()).count() }}
  }}
  "#, name = cfg.name)
  }

  // ─── mm/mod.rs ────────────────────────────────────────────────────────────────

  pub fn kernel_mm(_cfg: &OsConfig) -> String {
      r#"//! Memory management
  extern crate alloc;

  pub mod allocator;
  pub use allocator::BumpAllocator;
  "#.into()
  }

  pub fn kernel_mm_allocator(_cfg: &OsConfig) -> String {
      r#"//! Simple bump allocator — replace with linked-list for production.
  use core::alloc::{GlobalAlloc, Layout};
  use core::cell::UnsafeCell;

  const HEAP_SIZE: usize = 4 * 1024 * 1024; // 4 MiB default

  pub struct BumpAllocator {
      heap:   UnsafeCell<[u8; HEAP_SIZE]>,
      offset: UnsafeCell<usize>,
  }

  unsafe impl Sync for BumpAllocator {}

  impl BumpAllocator {
      pub const fn new() -> Self {
          Self { heap: UnsafeCell::new([0u8; HEAP_SIZE]), offset: UnsafeCell::new(0) }
      }
  }

  unsafe impl GlobalAlloc for BumpAllocator {
      unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
          let off   = &mut *self.offset.get();
          let align = layout.align();
          let start = (*off + align - 1) & !(align - 1);
          let end   = start + layout.size();
          if end > HEAP_SIZE { return core::ptr::null_mut(); }
          *off = end;
          (self.heap.get() as *mut u8).add(start)
      }
      unsafe fn dealloc(&self, _ptr: *mut u8, _layout: Layout) {}
  }

  #[global_allocator]
  pub static ALLOCATOR: BumpAllocator = BumpAllocator::new();
  "#.into()
  }

  // ─── sched/mod.rs ─────────────────────────────────────────────────────────────

  pub fn kernel_sched(_cfg: &OsConfig) -> String {
      r#"//! Round-robin scheduler stub
  extern crate alloc;
  use alloc::collections::VecDeque;

  pub struct Scheduler {
      queue: VecDeque<u64>, // sub-kernel ids
  }
  impl Scheduler {
      pub fn new() -> Self { Self { queue: VecDeque::new() } }
      pub fn enqueue(&mut self, id: u64) { self.queue.push_back(id); }
      pub fn next(&mut self) -> Option<u64> {
          let id = self.queue.pop_front()?;
          self.queue.push_back(id);
          Some(id)
      }
      pub fn len(&self) -> usize { self.queue.len() }
  }
  "#.into()
  }

  // ─── ipc/mod.rs ───────────────────────────────────────────────────────────────

  pub fn kernel_ipc(_cfg: &OsConfig) -> String {
      r#"//! Basic IPC channel
  extern crate alloc;
  use alloc::collections::VecDeque;
  use alloc::vec::Vec;

  pub const MAX_MSG: usize = 4096;

  #[derive(Debug)]
  pub enum IpcError { ChannelFull, ChannelEmpty, PayloadTooLarge }

  pub struct Channel {
      pub id:    u64,
      buf:       VecDeque<Vec<u8>>,
      capacity:  usize,
  }
  impl Channel {
      pub fn new(id: u64) -> Self { Self { id, buf: VecDeque::new(), capacity: 64 } }
      pub fn send(&mut self, msg: Vec<u8>) -> Result<(), IpcError> {
          if msg.len() > MAX_MSG         { return Err(IpcError::PayloadTooLarge); }
          if self.buf.len() >= self.capacity { return Err(IpcError::ChannelFull); }
          self.buf.push_back(msg); Ok(())
      }
      pub fn recv(&mut self) -> Result<Vec<u8>, IpcError> {
          self.buf.pop_front().ok_or(IpcError::ChannelEmpty)
      }
      pub fn pending(&self) -> usize { self.buf.len() }
  }
  "#.into()
  }

  // ─── core crate ───────────────────────────────────────────────────────────────

  pub fn core_cargo(cfg: &OsConfig) -> String {
      format!(r#"[package]
  name        = "{slug}-core"
  description = "Shared types and traits for {name}"
  version.workspace = true
  edition.workspace = true
  authors.workspace = true
  license.workspace = true

  [lib]
  path = "src/lib.rs"
  "#, slug = cfg.slug, name = cfg.name)
  }

  pub fn core_lib(cfg: &OsConfig) -> String {
      format!(r#"//! {name} core — shared types and traits
  #![no_std]
  extern crate alloc;

  pub mod types;
  pub use types::*;
  "#, name = cfg.name)
  }

  pub fn core_types(cfg: &OsConfig) -> String {
      format!(r#"//! Fundamental types shared across all {name} crates
  extern crate alloc;
  use alloc::string::String;

  /// Unique node identifier in a sovereign P2P network
  pub type NodeId = [u8; 32];

  /// Monotonic clock tick
  pub type Tick = u64;

  /// Physical memory address
  pub type PhysAddr = usize;

  /// Virtual memory address  
  pub type VirtAddr = usize;

  /// Result type alias for {name} errors
  pub type OsResult<T> = Result<T, OsError>;

  #[derive(Debug, Clone)]
  pub enum OsError {{
      OutOfMemory,
      PermissionDenied,
      NotFound,
      InvalidArgument,
      IoError,
      Other(String),
  }}
  "#, name = cfg.name)
  }

  // ─── boot crate ───────────────────────────────────────────────────────────────

  pub fn boot_cargo(cfg: &OsConfig) -> String {
      format!(r#"[package]
  name        = "{slug}-boot"
  description = "{name} bootloader (Ring -1 UEFI entry)"
  version.workspace = true
  edition.workspace = true
  authors.workspace = true
  license.workspace = true

  [[bin]]
  name = "{slug}-boot"
  path = "src/main.rs"

  [dependencies]
  {slug}-kernel = {{ path = "../../kernel/{slug}" }}
  {slug}-core   = {{ path = "../../core/{slug}-core" }}
  log           = {{ workspace = true }}

  [profile.dev]
  panic = "abort"

  [profile.release]
  panic     = "abort"
  lto       = true
  opt-level = "s"
  strip     = true
  "#, slug = cfg.slug, name = cfg.name)
  }

  pub fn boot_main(cfg: &OsConfig) -> String {
      let arch_halt = match cfg.arch {
          TargetArch::X86_64 => r#"loop { unsafe { core::arch::asm!("hlt"); } }"#,
          TargetArch::Arm64  => r#"loop { unsafe { core::arch::asm!("wfi"); } }"#,
          TargetArch::RiscV  => r#"loop { unsafe { core::arch::asm!("wfi"); } }"#,
          TargetArch::All    => r#"loop { unsafe { core::arch::asm!("hlt"); } }"#,
      };
      format!(r#"//! {name} bootloader entry point
  #![no_std]
  #![no_main]

  use {slug}_kernel::{{SubKernelManager, cap::{{CapabilityToken, CapRight}}}};
  use {slug}_kernel::subkernel::instance::SubKernelConfig;
  use {slug}_kernel::mm::ALLOCATOR;

  #[no_mangle]
  pub extern "C" fn _start() -> ! {{
      // Initialise the kernel
      let mut manager = SubKernelManager::new();

      // Spawn the init sub-kernel with full capabilities
      let root_cap = CapabilityToken::root();
      let _ = manager.spawn(
          SubKernelConfig {{ name: "init", mem_mb: 64 }},
          root_cap,
      );

      // Main kernel loop
      loop {{
          manager.tick_all();
          {halt}
      }}
  }}

  #[panic_handler]
  fn panic(_info: &core::panic::PanicInfo) -> ! {{
      {halt}
  }}
  "#, name = cfg.name, slug = cfg.slug, halt = arch_halt)
  }

  // ─── README.md ───────────────────────────────────────────────────────────────

  pub fn workspace_readme(cfg: &OsConfig) -> String {
      let features = if cfg.features.enabled_list().is_empty() {
          String::from("- Minimal kernel (cap system, scheduler, IPC, sub-kernel manager)")
      } else {
          cfg.features.enabled_list().iter()
              .map(|f| format!("- {}", f))
              .collect::<Vec<_>>()
              .join("\n")
      };

      format!(r#"# {name}

  > A sovereign OS generated by **Oxidiser** — the Re-Rust OS scaffolding tool.

  ## Architecture

  ```
  {name} Sovereign OS
  ├── kernel/{slug}       — master kernel (cap, mm, sched, ipc, sub-kernels)
  ├── core/{slug}-core    — shared types and traits
  ├── boot/{slug}-boot    — Ring -1 UEFI bootloader entry
  └── ...                 — optional feature modules
  ```

  ## Features enabled

  {features}

  ## Target architecture

  **{arch}**

  ## Build

  ```bash
  # Install the bare-metal target
  rustup target add {target}

  # Build the whole workspace
  cargo build --release

  # Build just the kernel
  cargo build -p {slug}-kernel --release
  ```

  ## Getting started

  Edit `kernel/{slug}/src/subkernel/manager.rs` to customise sub-kernel spawn logic.
  Edit `boot/{slug}-boot/src/main.rs` to add early hardware init.

  ---

  _Generated by [Oxidiser](https://github.com/Syedsmaeel/Proj.re-rust) — part of the Re-Rust / Timux ecosystem._
  "#,
          name    = cfg.name,
          slug    = cfg.slug,
          features= features,
          arch    = cfg.arch.display(),
          target  = cfg.arch.rust_target(),
      )
  }

  // ─── .gitignore ───────────────────────────────────────────────────────────────

  pub fn gitignore() -> &'static str {
      "/target/\n.DS_Store\nThumbs.db\n*.swp\n*.bak\n"
  }
  