[package]
name = "sushi"
description = "An elite, raw-fish Terminal UI (TUI) framework"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
re-core.workspace = true
ratatui = "0.26"
crossterm = "0.27"
anyhow.workspace = true

[[bin]]
name = "sushi-tui"
path = "examples/tui_demo.rs"
