[package]
name = "re-core"
description = "Shared primitives for Proj.re-rust"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# Minimal dependencies for no_std
log = "0.4"
serde = { version = "1", default-features = false, features = ["derive"] }
