name: Ephemeral Heavy Rust Terminal
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  launch-shell:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Prepare Local SSH Keys
      run: |
        mkdir -p ~/.ssh
        ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa

    - name: Launch Official Tmate Client
      uses: mxschmitt/action-tmate@v3
      with:
        # Only the GitHub user who triggered the run can connect.
        limit-access-to-actor: true
