name: Ephemeral Heavy Rust Terminal
on: 
  workflow_dispatch:
  push:

jobs:
  launch-shell:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v4

    - name: Prepare Local SSH Keys
      run: |
        mkdir -p ~/.ssh
        ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa

    - name: Launch Official Tmate Client
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false
