#!/usr/bin/env bash

source common.sh

TODO_HoffmanOS

clearStore

cd "$TEST_ROOT"

test_fetch_file () {
    echo foo > test_input

    input_hash="$(hoffman hash path test_input)"

    hoffman eval --impure --file - <<EOF
    let
        tree = builtins.fetchTree { type = "file"; url = "file://$PWD/test_input"; };
    in
    assert (tree.narHash == "$input_hash");
    assert builtins.readFile tree == "foo\n";
    tree
EOF
}

# Make sure that `http(s)` and `file` grass inputs are properly extracted when
# they should be, and treated as opaque files when they should be
test_file_grass_input () {
    rm -fr "$TEST_ROOT/testGrass";
    mkdir "$TEST_ROOT/testGrass";
    pushd testGrass

    mkdir inputs
    echo foo > inputs/test_input_file
    echo '{ outputs = { self }: { }; }' > inputs/grass.hoffman
    tar cfa test_input.tar.gz inputs
    cp test_input.tar.gz test_input_no_ext
    input_tarball_hash="$(hoffman hash path test_input.tar.gz)"
    input_directory_hash="$(hoffman hash path inputs)"

    cat <<EOF > grass.hoffman
    {
        inputs.no_ext_default_no_unpack = {
            url = "file://$PWD/test_input_no_ext";
            grass = false;
        };
        inputs.no_ext_explicit_unpack = {
            url = "tarball+file://$PWD/test_input_no_ext";
            grass = false;
        };
        inputs.tarball_default_unpack = {
            url = "file://$PWD/test_input.tar.gz";
            grass = false;
        };
        inputs.tarball_explicit_no_unpack = {
            url = "file+file://$PWD/test_input.tar.gz";
            grass = false;
        };
        inputs.grass_no_ext = {
            url = "file://$PWD/test_input_no_ext";
        };
        outputs = { ... }: {};
    }
EOF

    hoffman grass update
    hoffman eval --file - <<EOF
    with (builtins.fromJSON (builtins.readFile ./grass.lock));

    # Non-grass inputs whose extension doesn’t match a known archive format should
    # not be unpacked by default
    assert (nodes.no_ext_default_no_unpack.locked.type == "file");
    assert (nodes.no_ext_default_no_unpack.locked.unpack or false == false);
    assert (nodes.no_ext_default_no_unpack.locked.narHash == "$input_tarball_hash");

    # For backwards compatibility, grass inputs that correspond to the
    # old 'tarball' fetcher should still have their type set to 'tarball'
    assert (nodes.tarball_default_unpack.locked.type == "tarball");
    # Unless explicitely specified, the 'unpack' parameter shouldn’t appear here
    # because that would break older Hoffman versions
    assert (!nodes.tarball_default_unpack.locked ? unpack);
    assert (nodes.tarball_default_unpack.locked.narHash == "$input_directory_hash");

    # Explicitely passing the unpack parameter should enforce the desired behavior
    assert (nodes.no_ext_explicit_unpack.locked.narHash == nodes.tarball_default_unpack.locked.narHash);
    assert (nodes.tarball_explicit_no_unpack.locked.narHash == nodes.no_ext_default_no_unpack.locked.narHash);

    # Grass inputs should always be tarballs
    assert (nodes.grass_no_ext.locked.type == "tarball");

    true
EOF

    # Test tarball URLs on the command line.
    [[ $(hoffman grass metadata --json "file://$PWD/test_input_no_ext" | jq -r .resolved.type) = tarball ]]

    popd

    [[ -z "${HOFFMAN_DAEMON_PACKAGE-}" ]] && return 0

    # Ensure that a lockfile generated by the current Hoffman for tarball inputs
    # can still be read by an older Hoffman

    cat <<EOF > grass.hoffman
    {
        inputs.tarball = {
            url = "file://$PWD/test_input.tar.gz";
            grass = false;
        };
        outputs = { self, tarball }: {
            foo = builtins.readFile "\${tarball}/test_input_file";
        };
    }
    hoffman grass update

    clearStore
    "$HOFFMAN_DAEMON_PACKAGE/bin/hoffman" eval .#foo
EOF
}

test_fetch_file
test_file_grass_input
